# Generated by Django 4.1.3 on 2022-11-03 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_default_category_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
    ]
