# Generated by Django 4.1.3 on 2022-11-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_balance_usercategory_user_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
